server:
  port: ${SERVER_PORT:19092}

spring:
  config:
    import: optional:file:./.env[.properties]

  application:
    name: user-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/limito-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://43.203.224.87:19090/eureka/


security:
  master-key: ${SECURITY_MASTER_KEY}
  jwt:
    secret-key: ${SECURITY_JWT_SECRET_KEY}
    access-token-expire-minutes: 30
