server:
  port: ${SERVER_PORT:19092}

spring:
  config:
    import: optional:file:./.env[.properties]

  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:15432}/${POSTGRES_DB:limito-db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


security:
  master-key: limito-master-1234

  jwt:
    secret-key: "N2Y5ZDgzNzMwZTU1ODFkMGNhNjE4YzY2YmI3M2ZlYmQ="
    access-token-expire-minutes: 30